development:
  adapter: postgresql
  encoding: unicode
  database: carboy_development
  pool: 5
  username: ethanschmertzler1
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: carboy_test
  pool: 5
  username: ethanschmertzler1
  password: